# Generated by Django 4.0.2 on 2022-05-14 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_final_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_order',
            name='company',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='final_order',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
